# Generated by Django 5.1.5 on 2025-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address the OTP was sent to.', max_length=254, unique=True)),
                ('otp', models.CharField(help_text='The 6-digit OTP.', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='Timestamp when this OTP will expire.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Storage',
                'verbose_name_plural': 'OTP Storage',
            },
        ),
    ]
