# Generated by Django 5.1.5 on 2025-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodInformation',
            fields=[
                ('eventid', models.TextField(primary_key=True, serialize=False)),
                ('gaugeid', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('peak_flood_level_m', models.DecimalField(decimal_places=3, max_digits=7)),
                ('peak_fl_date', models.DateTimeField()),
                ('num_peak_fl', models.IntegerField()),
                ('peak_discharge_q_cumec', models.DecimalField(decimal_places=2, max_digits=7)),
                ('peak_discharge_date', models.DateTimeField()),
                ('flood_volume_cumec', models.DecimalField(decimal_places=2, max_digits=9)),
                ('event_duration_days', models.IntegerField()),
                ('time_to_peak_days', models.IntegerField()),
                ('recession_time_day', models.IntegerField()),
                ('flood_type', models.TextField()),
            ],
            options={
                'db_table': 'flood_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaugeid', models.IntegerField()),
                ('indofloods_gid', models.IntegerField()),
                ('station_name', models.TextField()),
                ('river_basin', models.TextField()),
                ('group', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('warning_level', models.DecimalField(decimal_places=14, max_digits=17)),
                ('danger_level', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('river_name_tributory_subtributory', models.TextField()),
                ('state', models.TextField()),
                ('reliability', models.TextField()),
                ('num_floods', models.IntegerField()),
                ('flood_months', models.TextField()),
                ('flow_availability', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'station_information',
                'managed': False,
            },
        ),
    ]
