# missingreport/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MissingPersonReportViewSet

# Create a router instance
router = DefaultRouter()

# Register the ViewSet with the router
# This generates URLs for list, create, retrieve, update, destroy
router.register(r'missing-persons', MissingPersonReportViewSet, basename='missingpersonreport')

# Define the urlpatterns for this app
urlpatterns = [
    # Include the URLs generated by the router
    # All paths will be relative to where this file is included in the main urls.py
    # e.g., if included as 'api/reports/', the list view will be '/api/reports/missing-persons/'
    path('', include(router.urls)),
]

# --- Remember to include this app's urls.py in your main project urls.py ---
# Example in main urls.py:
# path('api/reports/', include('missingreport.urls')), # Use 'missingreport.urls'
