# Generated by Django 5.1.5 on 2025-01-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastDisaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('disaster_type', models.CharField(max_length=100)),
                ('total_deaths', models.IntegerField()),
                ('total_injured', models.IntegerField()),
                ('total_affected', models.BigIntegerField()),
                ('loss_inr', models.BigIntegerField()),
            ],
            options={
                'db_table': 'past_disasters',
            },
        ),
    ]
