# Generated by Django 5.1.5 on 2025-01-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_disasters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastdisaster',
            options={'managed': False},
        ),
    ]
