# Generated by Django 5.1.5 on 2025-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_disasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdacsdisasterevent',
            name='report_url',
            field=models.URLField(blank=True, help_text='URL to the detailed GDACS report page.', max_length=1024, null=True),
        ),
    ]
