# Generated by Django 5.1.5 on 2025-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_disasters', '0002_gdacsdisasterevent_report_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdacsdisasterevent',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='Country name(s).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gdacsdisasterevent',
            name='link',
            field=models.URLField(help_text='Link to the GDACS event page.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='gdacsdisasterevent',
            name='population',
            field=models.CharField(blank=True, help_text='Affected population estimate (textual).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gdacsdisasterevent',
            name='severity',
            field=models.CharField(blank=True, help_text="Severity description (e.g., 'M 7.1').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gdacsdisasterevent',
            name='title',
            field=models.CharField(help_text='Title of the event from the feed.', max_length=500),
        ),
    ]
