# Generated by Django 5.1.5 on 2025-04-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_disasters', '0003_alter_gdacsdisasterevent_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdacsdisasterevent',
            options={'ordering': [models.OrderBy(models.F('pubDate'), descending=True, nulls_last=True), models.OrderBy(models.F('fromdate'), descending=True, nulls_last=True)], 'verbose_name': 'GDACS Disaster Event', 'verbose_name_plural': 'GDACS Disaster Events'},
        ),
    ]
