# Generated by Django 5.1.5 on 2025-04-25 10:49

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the missing person.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the person and circumstances.')),
                ('identification_marks', models.TextField(blank=True, help_text='Distinctive identification marks (optional).', null=True)),
                ('last_seen_location', models.TextField(help_text='Where and when the person was last seen.')),
                ('reporter_contact_info', models.CharField(help_text='Contact information provided by the reporter for this case.', max_length=255)),
                ('identity_card_image', cloudinary.models.CloudinaryField(blank=True, help_text="Uploaded photo of the missing person's identity card (optional).", max_length=255, null=True, verbose_name='missing_persons/identity_cards')),
                ('person_photo', cloudinary.models.CloudinaryField(help_text='Uploaded photo of the missing person.', max_length=255, verbose_name='missing_persons/photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(help_text='The user who submitted this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_missing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Person Report',
                'verbose_name_plural': 'Missing Person Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
