# Generated by Django 5.1.5 on 2025-05-19 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingreport', '0002_missingpersonreport_additional_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonreport',
            name='agency_current_location_of_person',
            field=models.TextField(blank=True, help_text='Current location of the person if different, as per agency.', null=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='agency_found_location',
            field=models.TextField(blank=True, help_text='Location where agency found the person.', null=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='agency_found_notes',
            field=models.TextField(blank=True, help_text='Additional notes from the agency regarding finding the person.', null=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='agency_person_condition',
            field=models.CharField(blank=True, choices=[('ALIVE', 'Alive and Well'), ('INJURED', 'Injured'), ('DECEASED', 'Deceased'), ('UNKNOWN', 'Condition Unknown')], help_text='Condition of the person when found by agency.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='marked_found_by_type',
            field=models.CharField(blank=True, choices=[('REPORTER', 'Reporter'), ('AGENCY', 'Agency'), ('OTHER', 'Other/Unknown')], help_text='Who marked the person as found (reporter or agency).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='marked_found_by_user',
            field=models.ForeignKey(blank=True, help_text='The specific user/agency who marked this report as found.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_reports_as_found', to=settings.AUTH_USER_MODEL),
        ),
    ]
