# Generated by Django 5.1.5 on 2025-05-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingreport', '0003_missingpersonreport_agency_current_location_of_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingpersonreport',
            name='found_date',
            field=models.DateField(blank=True, help_text='Date when the person was marked/confirmed found.', null=True),
        ),
        migrations.AddField(
            model_name='missingpersonreport',
            name='is_found',
            field=models.BooleanField(db_index=True, default=False, help_text='Is the person marked as found?'),
        ),
    ]
