# Generated by Django 5.1.5 on 2025-02-28 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingAgencies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agency_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('last_seen_location', models.CharField(max_length=500)),
                ('identification_marks', models.TextField()),
                ('description', models.TextField(help_text='Detailed description of the missing person')),
                ('person_photo', models.ImageField(upload_to='missing_persons/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('id_card_photo', models.ImageField(blank=True, null=True, upload_to='missing_persons/id_cards/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('has_id_card', models.BooleanField(default=False)),
                ('has_person_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Person Report',
                'verbose_name_plural': 'Missing Person Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
