# Generated by Django 5.1.5 on 2025-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_event_user_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeline_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='TimelineItem',
        ),
    ]
