# Generated by Django 5.1.5 on 2025-04-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_event_timeline_items_delete_timelineitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='existingagencies',
            table='existing_agencies',
        ),
    ]
