# Generated by Django 5.1.5 on 2025-04-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_volunteerinterest_agencymemberpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerinterest',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True if the agency accepts this volunteer interest.'),
        ),
    ]
