# Generated by Django 5.1.5 on 2025-04-18 19:20

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_volunteerinterest_is_accepted'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('user', models.OneToOneField(help_text='The agency user account this profile belongs to.', limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agency_name', models.CharField(help_text='Formal name of the agency.', max_length=255)),
                ('contact1', models.CharField(help_text='Primary contact number.', max_length=20)),
                ('contact2', models.CharField(blank=True, help_text='Secondary contact number (optional).', max_length=20, null=True)),
                ('agency_type', models.CharField(help_text='Type of the agency (e.g., NGO, Government, Private).', max_length=100)),
                ('website', models.URLField(blank=True, help_text="Agency's official website (optional).", null=True)),
                ('date_of_establishment', models.DateField(help_text='Date the agency was established.')),
                ('volunteers', models.PositiveIntegerField(blank=True, help_text='Approximate number of volunteers (optional).', null=True)),
                ('address', models.TextField(help_text='Full operational address.')),
                ('district', models.CharField(help_text='District where the agency is located.', max_length=100)),
                ('state', models.CharField(help_text='State where the agency is located.', max_length=100)),
                ('lat', models.FloatField(blank=True, help_text="Latitude of the agency's location.", null=True)),
                ('lng', models.FloatField(blank=True, help_text="Longitude of the agency's location.", null=True)),
                ('description', models.TextField(help_text="Detailed description of the agency's activities and mission.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency Profile',
                'verbose_name_plural': 'Agency Profiles',
            },
        ),
        migrations.CreateModel(
            name='AgencyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Image uploaded for the agency profile.', max_length=255, verbose_name='agency_images')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agency_profile', models.ForeignKey(help_text='The agency profile these images belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.agencyprofile')),
            ],
            options={
                'verbose_name': 'Agency Image',
                'verbose_name_plural': 'Agency Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
