# Generated by Django 5.1.5 on 2025-04-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agencyprofile_agencyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingPersonReport',
        ),
    ]
