# Generated by Django 5.1.5 on 2025-05-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_delete_missingpersonreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='district',
        ),
    ]
